[tool.poetry]
name = "hydra-lsp"
version = "0.1.0"
description = ""
authors = ["Andrii Zhuravchak <retsediv1@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pygls = "^1.1.1"
lsprotocol = "^2023.0.0b1"


[tool.poetry.scripts]
hydra-lsp = "hydra_lsp.server:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
